### PING 
GET http://localhost:3000/ping

###! DIARIES
### GET ALL
GET http://localhost:3000/api/diaries 

### CREATE NEW
POST http://localhost:3000/api/diaries
Content-Type: application/json

{
  "date": "2025-07-06",
  "weather": "sunny",
  "visibility": "good",
  "comment": "good stuf but scary"
}

### FIND BY ID
GET http://localhost:3000/api/diaries/5